version: "3.11"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=holiday
      - POSTGRES_USER=holiday
      - POSTGRES_PASSWORD=Sylwia1234!
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code/
    ports:
      - "8000:8000"
    depends_on:
      - db




