# Generated by Django 4.2.2 on 2023-06-29 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='title',
            new_name='country',
        ),
    ]
